SeqLib: BamRecord Class Reference
BamRecord Class Reference
Class to store and interact with a SAM alignment record.
#include <BamRecord.h>
Public Member Functions
BamRecord (const std::string &name, const std::string &seq, const GenomicRegion *gr, const Cigar &cig)
Construct a BamRecord manually from a name, sequence, cigar and location.
void init ()
Construct an empty BamRecord by calling bam_init1()
bool isEmpty () const
Check if a read is empty (not initialized) true if read was not initialized with any values.
void assign (bam1_t *a)
Explicitly pass a bam1_t to the BamRecord.
BamRecord ()
Make a BamRecord with no memory allocated and a null header.
bool ReverseFlag () const
BamRecord is aligned on reverse strand.
bool MateReverseFlag () const
BamRecord has mate aligned on reverse strand.
bool Interchromosomal () const
BamRecord has is an interchromosomal alignment.
bool DuplicateFlag () const
BamRecord is a duplicate.
bool SecondaryFlag () const
BamRecord is a secondary alignment.
bool PairedFlag () const
BamRecord is paired.
int PairOrientation () const
Get the relative pair orientations.
bool QCFailFlag () const
BamRecord is failed QC.
bool MappedFlag () const
BamRecord is mapped.
bool MateMappedFlag () const
BamRecord mate is mapped.
bool PairMappedFlag () const
BamRecord is mapped and mate is mapped and in pair.
bool ProperPair () const
BamRecord is mapped in proper pair.
bool ProperOrientation () const
BamRecord has proper orientation (FR)
int32_t CountNBases () const
Count the total number of N bases in this sequence.
void QualityTrimmedSequence (int32_t qualTrim, int32_t &startpoint, int32_t &endpoint) const
Trim the sequence down by removing bases from ends with low quality scores.
std::string QualitySequence () const
Retrieve the quality trimmed seqeuence from QT tag if made.
int32_t Position () const
Get the alignment position.
int32_t MatePosition () const
Get the alignment position of mate.
int32_t CountBWASecondaryAlignments () const
Count the number of secondary alignments by looking at XA tag.
int32_t CountBWAChimericAlignments () const
Count the number of chimeric alignments by looking at XP and SA tags.
int32_t PositionEnd () const
Get the end of the alignment.
int32_t ChrID () const
Get the chromosome ID of the read.
int32_t MateChrID () const
Get the chrosome ID of the mate read.
int32_t MapQuality () const
Get the mapping quality.
void SetMapQuality (int32_t m)
Set the mapping quality.
void SetChrID (int32_t i)
Set the chr id.
void SetChrIDMate (int32_t i)
Set the chr id of mate.
void SetPositionMate (int32_t i)
Set the position of the mate read.
void SetPairMappedFlag ()
Set the pair mapped flag on.
void SetMateReverseFlag ()
Set the mate reverse flag on.
int32_t CigarSize () const
Get the number of cigar fields.
bool FirstFlag () const
Check if this read is first in pair.
std::string Qname () const
Get the qname of this read as a string.
char * QnameChar () const
Get the qname of this read as a char array.
uint32_t AlignmentFlag () const
Get the full alignment flag for this read.
int32_t InsertSize () const
Get the insert size for this read.
std::string ParseReadGroup () const
Get the read group, first from qname, then by RG tag.
int32_t FullInsertSize () const
Get the insert size, absolute value, and always taking into account read length.
int32_t Length () const
Get the number of query bases of this read (aka length)
void SmartAddTag (const std::string &tag, const std::string &val)
Append a tag with new value, delimited by 'x'.
void SetQname (const std::string &n)
Set the query name.
void SetQualities (const std::string &n, int offset)
void SetSequence (const std::string &seq)
Set the sequence name.
void SetCigar (const Cigar &c)
Set the cigar field explicitly.
GenomicRegion AsGenomicRegion () const
Return read as a GenomicRegion.
GenomicRegion AsGenomicRegionMate () const
Return mate read as a GenomicRegion.
int NumAlignedBases () const
Return the number of "aligned bases" in the same style as BamTools.
uint32_t MaxInsertionBases () const
Return the max single insertion size on this cigar.
uint32_t MaxDeletionBases () const
Return the max single deletion size on this cigar.
uint32_t NumMatchBases () const
Get the number of matched bases in this alignment.
Cigar GetCigar () const
Retrieve the CIGAR as a more managable Cigar structure.
Cigar GetReverseCigar () const
Retrieve the inverse of the CIGAR as a more managable Cigar structure.
void ClearSeqQualAndTags ()
Remove the sequence, quality and alignment tags.
std::string Sequence () const
Get the sequence of this read as a string.
double MeanPhred () const
Return the mean phred score.
BamRecord (const std::string &name, const std::string &seq, const std::string &ref, const GenomicRegion *gr)
Do a smith waterman alignment.
std::string Qualities () const
Get the quality scores of this read as a string.
int32_t AlignmentPositionReverse () const
Get the start of the alignment on the read, by removing soft-clips Do this in the reverse orientation though.
int32_t AlignmentEndPositionReverse () const
Get the end of the alignment on the read, by removing soft-clips Do this in the reverse orientation though.
int32_t AlignmentPosition () const
Get the start of the alignment on the read, by removing soft-clips.
int32_t AlignmentEndPosition () const
Get the end of the alignment on the read, by removing soft-clips.
int32_t NumSoftClip () const
Get the number of soft clipped bases.
int32_t NumHardClip () const
Get the number of hard clipped bases.
int32_t NumClip () const
Get the number of clipped bases (hard clipped and soft clipped)
std::string GetZTag (const std::string &tag) const
Get a string (Z) tag.
std::vector< int > GetSmartIntTag (const std::string &tag) const
Get a vector of type int from a Z tag delimited by "^".
std::vector< double > GetSmartDoubleTag (const std::string &tag) const
Get a vector of type double from a Z tag delimited by "x".
std::vector< std::string > GetSmartStringTag (const std::string &tag) const
Get a vector of strings from a Z tag delimited by "^".
int32_t GetIntTag (const std::string &tag) const
Get an int (i) tag.
void AddZTag (std::string tag, std::string val)
Add a string (Z) tag.
void AddIntTag (const std::string &tag, int32_t val)
Add an int (i) tag.
void SetID (int32_t id)
Set the chr id number.
void SetPosition (int32_t pos)
Set the alignment start position.
std::string CigarString () const
Convert CIGAR to a string.
std::string ChrName () const
Return a human readable chromosome name assuming chr is indexed from 0 (eg id 0 return "1")
std::string ChrName (const SeqLib::BamHeader &h) const
Retrieve the human readable chromosome name.
std::string Brief () const
Return a short description (chr:pos) of this read.
std::string BriefMate () const
Return a short description (chr:pos) of this read's mate.
void RemoveTag (const char *tag)
Strip a particular alignment tag.
void RemoveAllTags ()
Strip all of the alignment tags.
bam1_t * raw () const
Return the raw pointer.
int OverlappingCoverage (const BamRecord &r) const
Return the number of bases on the reference that are covered by a match (M) on both reads.
Friends
class BLATWraper
class BWAWrapper
std::ostream & operator<< (std::ostream &out, const BamRecord &r)
Print a SAM-lite record for this alignment.
Detailed Description
Class to store and interact with a SAM alignment record.
HTSLibrary reads are stored in the bam1_t struct. Memory allocation is taken care of by bam1_t init, and deallocation by destroy_bam1. This class is a C++ interface that automatically takes care of memory management for these C allocs/deallocs. The only member of BamRecord is a bam1_t object. Alloc/dealloc is taken care of by the constructor and destructor.
Constructor & Destructor Documentation
BamRecord (const std::string & name, const std::string & seq, const GenomicRegion * gr, const Cigar & cig)
Construct a BamRecord manually from a name, sequence, cigar and location.
Parameters
name Name of the read
seq Sequence of the read (compsed of ACTG or N).
gr Location of the alignment
cig Cigar alignment
Exceptions
Throws an invalid_argument exception if length of seq is not commensurate with number of query-bases consumed in cigar.
Throws an invalid_argument exception if width of gr is not commensurate with number of reference-bases consumed in cigar.
Member Function Documentation
void AddIntTag (const std::string & tag, int32_t val) inline
Add an int (i) tag.
Parameters
tag Name of the tag. eg "XP"
val Value for the tag
void AddZTag (std::string tag, std::string val)
Add a string (Z) tag.
Parameters
tag Name of the tag. eg "XP"
val Value for the tag
void assign (bam1_t * a)
Explicitly pass a bam1_t to the BamRecord.
The BamRecord now controls the memory, and will delete at destruction
Parameters
a An allocated bam1_t
std::string ChrName (const SeqLib::BamHeader & h) const inline
Retrieve the human readable chromosome name.
Note that this requires that the header not be empty. If it is empty, assumes this ia chr1 based reference
Exceptions
Throws an out_of_range exception if chr id is not in dictionary
Returns
Empty string if chr id < 0, otherwise chromosome name from dictionary.
References BamHeader::IDtoName(), and BamHeader::isEmpty().
void ClearSeqQualAndTags ()
Remove the sequence, quality and alignment tags.
Make a more compact alignment stucture, without the string data
int32_t CountBWAChimericAlignments () const
Count the number of chimeric alignments by looking at XP and SA tags.
Note
A secondary alignment is an alternative mapping. This may not work for non-BWA aligners that may not place the XP/SA tags. BWA-MEM used the XP tag prior to v0.7.5, and SA aftewards.
int32_t CountBWASecondaryAlignments () const
Count the number of secondary alignments by looking at XA tag.
Note
A secondary alignment is an alternative mapping. This may not work for non-BWA aligners that may not place the XA tag.
int32_t GetIntTag (const std::string & tag) const inline
Get an int (i) tag.
Parameters
tag Name of the tag. eg "XP"
Returns
The value stored in the tag. Returns 0 if it does not exist.
std::vector<double> GetSmartDoubleTag (const std::string & tag) const
Get a vector of type double from a Z tag delimited by "x".
Parameters
tag Name of the tag eg "AL"
Returns
A vector of double elems, retrieved from the "^" delimited Z tag
Exceptions
Throws an invalid_argument if cannot convert delimited field val to double
std::vector<int> GetSmartIntTag (const std::string & tag) const
Get a vector of type int from a Z tag delimited by "^".
Parameters
tag Name of the tag eg "AL"
Returns
A vector of ints, retrieved from the x delimited Z tag
Exceptions
Throws an invalid_argument if cannot convert delimited field val to int
std::vector<std::string> GetSmartStringTag (const std::string & tag) const
Get a vector of strings from a Z tag delimited by "^".
Parameters
tag Name of the tag eg "CN"
Returns
A vector of strngs, retrieved from the x delimited Z tag
std::string GetZTag (const std::string & tag) const
Get a string (Z) tag.
Parameters
tag Name of the tag. eg "XP"
Returns
The value stored in the tag. Returns empty string if it does not exist.
Referenced by BamRecord::ParseReadGroup().
int NumAlignedBases () const inline
Return the number of "aligned bases" in the same style as BamTools.
BamTools reports AlignedBases, which for example returns the literal strings (for diff CIGARs): 3S5M - CTG 5M - CTAGC 3M1D3M - ATG-TGA 3M1I3M - ATGCTGA
Returns
The number of M, D, X, = and I bases
int PairOrientation () const inline
Get the relative pair orientations.
0 - FR (RFORIENTATION) (lower pos read is Fwd strand, higher is reverse) 1 - FF (FFORIENTATION) 2 - RF (RFORIENTATION) 3 - RR (RRORIENTATION) 4 - Undefined (UDORIENTATION) (unpaired or one/both is unmapped)
References BamRecord::MatePosition(), BamRecord::MateReverseFlag(), BamRecord::PairMappedFlag(), BamRecord::Position(), and BamRecord::ReverseFlag().
std::string ParseReadGroup () const inline
Get the read group, first from qname, then by RG tag.
Returns
empty string if no readgroup found
References BamRecord::GetZTag(), and BamRecord::Qname().
std::string QualitySequence () const
Retrieve the quality trimmed seqeuence from QT tag if made.
Otherwise return normal seq
void QualityTrimmedSequence (int32_t qualTrim, int32_t & startpoint, int32_t & endpoint) const
Trim the sequence down by removing bases from ends with low quality scores.
Stores the trimmed sequence in the GV tag, but does not affect any other part of read.
Parameters
qualTrim Minimal quality score, zero-based (eg # == 2)
startpoint Returns the new starting point for the sequence
endpoint Return the new ending point for the sequence
void RemoveTag (const char * tag) inline
Strip a particular alignment tag.
Parameters
tag Tag to remove
void SetID (int32_t id) inline
Set the chr id number.
Parameters
id Chromosome id. Typically is 0 for chr1, etc
void SetPosition (int32_t pos) inline
Set the alignment start position.
Parameters
pos Alignment start position
The documentation for this class was generated from the following file:
SeqLib/BamRecord.h