SnowTools: BamRead Class Reference
BamRead Class Reference
Class to store and interact with an HTSLib bam1_t read.
#include <BamRead.h>
Public Member Functions
BamRead (const std::string &name, const std::string &seq, const GenomicRegion *gr, const Cigar &cig)
Construct a BamRead with perfect "alignment".
void init ()
Construct an empty BamRead by calling bam_init1()
bool isEmpty () const
Check if a read is empty (not initialized) true if read was not initialized with any values.
void assign (bam1_t *a)
Explicitly pass a bam1_t to the BamRead.
BamRead ()
Make a BamRead with no memory allocated and a null header.
bool ReverseFlag () const
BamRead is aligned on reverse strand.
bool MateReverseFlag () const
BamRead has mate aligned on reverse strand.
bool Interchromosomal () const
BamRead has is an interchromosomal alignment.
bool DuplicateFlag () const
BamRead is a duplicate.
bool SecondaryFlag () const
BamRead is a secondary alignment.
bool PairedFlag () const
BamRead is paired.
int PairOrientation () const
Get the relative pair orientations.
bool QCFailFlag () const
BamRead is failed QC.
bool MappedFlag () const
BamRead is mapped.
bool MateMappedFlag () const
BamRead mate is mapped.
bool PairMappedFlag () const
BamRead is mapped and mate is mapped and in pair.
bool ProperPair () const
BamRead is mapped in proper pair.
bool ProperOrientation () const
BamRead has proper orientation (FR)
int32_t CountNBases () const
Count the total number of N bases in this sequence.
void QualityTrimmedSequence (int32_t qualTrim, int32_t &startpoint, int32_t &endpoint) const
Trim the sequence down by removing bases from ends with low quality scores.
std::string QualitySequence () const
Retrieve the quality trimmed seqeuence from QT tag if made.
int32_t Position () const
Get the alignment position.
int32_t MatePosition () const
Get the alignment position of mate.
int32_t CountSecondaryAlignments () const
Count the number of secondary alignments by looking at XA and XP tags.
int32_t PositionEnd () const
Get the end of the alignment.
int32_t ChrID () const
Get the chromosome ID of the read.
int32_t MateChrID () const
Get the chrosome ID of the mate read.
int32_t MapQuality () const
Get the mapping quality.
void SetMapQuality (int32_t m)
Set the mapping quality.
int32_t CigarSize () const
Get the number of cigar fields.
bool FirstFlag () const
Check if this read is first in pair.
std::string Qname () const
Get the qname of this read as a string.
char * QnameChar () const
Get the qname of this read as a char array.
uint32_t AlignmentFlag () const
Get the full alignment flag for this read.
int32_t InsertSize () const
Get the insert size for this read.
std::string ParseReadGroup () const
Get the read group, first from qname, then by RG tag.
int32_t FullInsertSize () const
Get the insert size, absolute value, and always taking into account read length.
int32_t Length () const
Get the number of query bases of this read (aka length)
void SmartAddTag (const std::string &tag, const std::string &val)
Append a tag with new value, delimited by 'x'.
void SetQname (const std::string &n)
Set the query name.
void SetSequence (const std::string &seq)
Set the sequence name.
GenomicRegion asGenomicRegion () const
Return read as a GenomicRegion.
GenomicRegion asGenomicRegionMate () const
Return mate as a GenomicRegion.
uint32_t MaxInsertionBases () const
Get the max insertion size on this cigar.
uint32_t MaxDeletionBases () const
Get the max deletion size on this cigar.
uint32_t NumMatchBases () const
Get the max deletion size on this cigar.
Cigar GetCigar () const
Retrieve the CIGAR as a more managable Cigar structure.
int32_t AlignmentLength () const
Get the length of the alignment (regardless of hardclipping)
Cigar GetReverseCigar () const
Retrieve the inverse of the CIGAR as a more managable Cigar structure.
void clearSeqQualAndTags ()
Remove the sequence, quality and alignment tags.
std::string Sequence () const
Get the sequence of this read as a string.
double MeanPhred () const
Return the mean phred score.
BamRead (const std::string &name, const std::string &seq, const std::string &ref, const GenomicRegion *gr)
Do a smith waterman alignment.
std::string Qualities () const
Get the quality scores of this read as a string.
int32_t AlignmentPositionReverse () const
Get the start of the alignment on the read, by removing soft-clips Do this in the reverse orientation though.
int32_t AlignmentEndPositionReverse () const
Get the end of the alignment on the read, by removing soft-clips Do this in the reverse orientation though.
int32_t AlignmentPosition () const
Get the start of the alignment on the read, by removing soft-clips.
int32_t AlignmentEndPosition () const
Get the end of the alignment on the read, by removing soft-clips.
int32_t NumSoftClip () const
Get the number of soft clipped bases.
int32_t NumHardClip () const
Get the number of hard clipped bases.
int32_t NumClip () const
Get the number of clipped bases (hard clipped and soft clipped)
std::string GetZTag (const std::string &tag) const
Get a string (Z) tag.
std::vector< int > GetSmartIntTag (const std::string &tag) const
Get a vector of ints from a Z tag delimited by "x".
std::vector< std::string > GetSmartStringTag (const std::string &tag) const
Get a vector of strings from a Z tag delimited by "x".
int32_t GetIntTag (const std::string &tag) const
Get an int (i) tag.
void AddZTag (std::string tag, std::string val)
Add a string (Z) tag.
void AddIntTag (const std::string &tag, int32_t val)
Add an int (i) tag.
void SetID (int32_t id)
Set the chr id number.
void SetPosition (int32_t pos)
Set the alignment start position.
std::string CigarString () const
Convert CIGAR to a string.
std::string ChrName (bam_hdr_t *h=nullptr) const
Retrieve the human readable chromosome name.
std::string Brief (bam_hdr_t *h=nullptr) const
Return a short description (chr:pos) of this read.
std::string BriefMate (bam_hdr_t *h=nullptr) const
Return a short description (chr:pos) of this read's mate.
void RemoveTag (const char *tag)
Strip a particular alignment tag.
void RemoveAllTags ()
Strip all of the alignment tags.
bam1_t * raw () const
Return the raw pointer.
bool coveredBase (int pos) const
Check if base at position on read is covered by alignment M or I (not clip)
bool coveredMatchBase (int pos) const
Check if base at position on read is covered by match only (M)
Public Attributes
std::shared_ptr< bam1_t > b
Friends
class BLATWraper
class BWAWrapper
std::ostream & operator<< (std::ostream &out, const BamRead &r)
Detailed Description
Class to store and interact with an HTSLib bam1_t read.
HTSLibrary reads are stored in the bam1_t struct. Memory allocation is taken care of by bam1_t init, and deallocation by destroy_bam1. This class is a C++ interface that automatically takes care of memory management for these C allocs/deallocs. The only member of BamRead is a bam1_t object. Alloc/dealloc is taken care of by the constructor and destructor.
Member Function Documentation
void AddIntTag (const std::string & tag, int32_t val) inline
Add an int (i) tag.
Parameters
tag Name of the tag. e.g. "XP"
val Value for the tag
void AddZTag (std::string tag, std::string val)
Add a string (Z) tag.
Parameters
tag Name of the tag. e.g. "XP"
val Value for the tag
void assign (bam1_t * a)
Explicitly pass a bam1_t to the BamRead.
The BamRead now controls the memory, and will delete at destruction
Parameters
a An allocated bam1_t
std::string ChrName (bam_hdr_t * h = nullptr) const inline
Retrieve the human readable chromosome name.
Note that this requires that the header not be empty. If it is empty, assumes this ia chr1 based reference
bool coveredBase (int pos) const
Check if base at position on read is covered by alignment M or I (not clip)
Example: Alignment with 50M10I10M20S – 0-79: true, 80+ false
Parameters
pos Position on base (0 is start)
Returns
true if that base is aligned (I or M)
bool coveredMatchBase (int pos) const
Check if base at position on read is covered by match only (M)
Example: Alignment with 10S50M20S – 0-9: false, 10-59: true, 60+: false
Parameters
pos Position on base (0 is start)
Returns
true if that base is aligned (M)
int32_t GetIntTag (const std::string & tag) const inline
Get an int (i) tag.
Parameters
tag Name of the tag. e.g. "XP"
Returns
The value stored in the tag. Returns 0 if it does not exist.
std::vector<int> GetSmartIntTag (const std::string & tag) const
Get a vector of ints from a Z tag delimited by "x".
Parameters
tag Name of the tag e.g. "AL"
Returns
A vector of ints, retrieved from the x delimited Z tag
std::vector<std::string> GetSmartStringTag (const std::string & tag) const
Get a vector of strings from a Z tag delimited by "x".
Parameters
tag Name of the tag e.g. "CN"
Returns
A vector of strngs, retrieved from the x delimited Z tag
std::string GetZTag (const std::string & tag) const
Get a string (Z) tag.
Parameters
tag Name of the tag. e.g. "XP"
Returns
The value stored in the tag. Returns empty string if it does not exist.
Referenced by BamRead::ParseReadGroup().
int PairOrientation () const inline
Get the relative pair orientations.
0 - FR (RFORIENTATION) (lower pos read is Fwd strand, higher is reverse) 1 - FF (FFORIENTATION) 2 - RF (RFORIENTATION) 3 - RR (RRORIENTATION) 4 - Undefined (UDORIENTATION) (unpaired or one/both is unmapped)
References BamRead::MatePosition(), BamRead::MateReverseFlag(), BamRead::PairMappedFlag(), BamRead::Position(), and BamRead::ReverseFlag().
std::string ParseReadGroup () const inline
Get the read group, first from qname, then by RG tag.
Returns
empty string if no readgroup found
References BamRead::GetZTag(), and BamRead::Qname().
std::string QualitySequence () const
Retrieve the quality trimmed seqeuence from QT tag if made.
Otherwise return normal seq
void RemoveTag (const char * tag) inline
Strip a particular alignment tag.
Parameters
tag Tag to remove
void SetID (int32_t id) inline
Set the chr id number.
Parameters
id Chromosome id. Typically is 0 for chr1, etc
void SetPosition (int32_t pos) inline
Set the alignment start position.
Parameters
pos Alignment start position
The documentation for this class was generated from the following file:
src/SnowTools/BamRead.h